name: Test Confusion Matrix
on:
  push:
    branches:
      - gh-pages
      - main
      - code-check-action
  pull_request: []
  workflow_dispatch:

jobs:
  code-check:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python modules
        run: |
          python3 -m pip install --upgrade pip setuptools wheel pyyaml==5.3.1 requests tensorflow-cpu seaborn scikit-learn pandas 

      - name: Install Code Checker
        run: |
          #python3 -m pip install --upgrade git+https://github.com/bpmweel/cce.git#egg=cce
          #fix to code checker which works on calls to imports inside functions
          python3 -m pip install --upgrade pytest
          wget -O /usr/local/bin/cce https://raw.githubusercontent.com/colinsauze/cce/master/cce/main.py 
          chmod 755 /usr/local/bin/cce

      - name: Checkout the lesson
        uses: actions/checkout@v2

      - name: Extract Episode 02
        run: |
          cce -f _episodes/02-keras.md > episode2.py 2>&1
          cat episode2.py
          grep ERROR episode2.py
        shell: bash {0} # opt out of fail-fast

      - name: Run Training of Episode 02
        run: |
          head ./episode2.py
          python episode2.py
        shell: bash {0} # opt out of fail-fast
          
